version: 2

updates:
  - package-ecosystem: pub
    directory: sample
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
