// Mocks generated by Mockito 5.2.0 from annotations
// in sample/test/widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:auth0_flutter/auth0_flutter.dart' as _i5;
import 'package:auth0_flutter/src/authentication_api.dart' as _i3;
import 'package:auth0_flutter/src/web_authentication.dart' as _i2;
import 'package:auth0_flutter_platform_interface/auth0_flutter_platform_interface.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeWebAuthentication_0 extends _i1.Fake
    implements _i2.WebAuthentication {}

class _FakeAuthenticationApi_1 extends _i1.Fake
    implements _i3.AuthenticationApi {}

class _FakeCredentials_2 extends _i1.Fake implements _i4.Credentials {}

/// A class which mocks [Auth0].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuth0 extends _i1.Mock implements _i5.Auth0 {
  MockAuth0() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WebAuthentication get webAuthentication =>
      (super.noSuchMethod(Invocation.getter(#webAuthentication),
          returnValue: _FakeWebAuthentication_0()) as _i2.WebAuthentication);
  @override
  _i3.AuthenticationApi get api => (super.noSuchMethod(Invocation.getter(#api),
      returnValue: _FakeAuthenticationApi_1()) as _i3.AuthenticationApi);
}

/// A class which mocks [WebAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebAuthentication extends _i1.Mock implements _i2.WebAuthentication {
  MockWebAuthentication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Credentials> login(
          {String? audience,
          Set<String>? scopes = const {},
          String? redirectUrl,
          String? organizationId,
          String? invitationUrl,
          String? scheme,
          bool? useEphemeralSession = false,
          Map<String, String>? parameters = const {},
          _i4.IdTokenValidationConfig? idTokenValidationConfig =
              const _i4.IdTokenValidationConfig()}) =>
      (super.noSuchMethod(
              Invocation.method(#login, [], {
                #audience: audience,
                #scopes: scopes,
                #redirectUrl: redirectUrl,
                #organizationId: organizationId,
                #invitationUrl: invitationUrl,
                #scheme: scheme,
                #useEphemeralSession: useEphemeralSession,
                #parameters: parameters,
                #idTokenValidationConfig: idTokenValidationConfig
              }),
              returnValue: Future<_i4.Credentials>.value(_FakeCredentials_2()))
          as _i6.Future<_i4.Credentials>);
  @override
  _i6.Future<void> logout({String? returnTo, String? scheme}) =>
      (super.noSuchMethod(
          Invocation.method(
              #logout, [], {#returnTo: returnTo, #scheme: scheme}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
}
